apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-manager
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-manager
  template:
    metadata:
      labels:
        app: kafka-manager
    spec:
      containers:
      - name: kafka-manager
        image: solsson/kafka-manager:latest
        ports:
        - containerPort: 80
        env:
        - name: ZK_HOSTS
          value: zookeeper.kafka:2181
        command:
        - ./bin/kafka-manager
        - -Dhttp.port=80